struct StepParams {
    gravity: vec4f,
    dt: f32,
    damping: f32,
    angular_damping: f32,
    body_count: u32,
    solve_iterations: u32,
    constraint_count: u32,
    relaxation: f32,
    slop: f32,
    restitution_threshold: f32,
    max_velocity: f32,
    max_angular_velocity: f32,
    dynamic_count: u32,
    sleep_velocity: f32,
    sleep_angular_velocity: f32,
    sleep_time: f32,
    wake_velocity: f32,
    friction_combine: u32,
    restitution_combine: u32,
    edit_run_count: u32,
    body_move_count: u32,
    constraint_move_count: u32,
    event_slot: u32,
    position_iterations: u32,
    contact_margin: f32,
    collider_count: u32,
    _pad3: u32,
}

struct BodyState {
    position: vec3f,
    _pad0: f32,
    prev_position: vec3f,
    _pad1: f32,
    orientation: vec4f,
    velocity: vec3f,
    _pad2: f32,
    angular_velocity: vec3f,
    _pad3: f32,
    force: vec3f,
    _pad4: f32,
    torque: vec3f,
    _pad5: f32,
    body_id: u32,
    generation: u32,
    sleep_timer: f32,
    sleeping: u32,
}

struct BodyDescriptor {
    inverse_mass: f32,
    linear_damping: f32,
    angular_damping: f32,
    gravity_scale: f32,
    sleep_velocity: f32,
    sleep_angular_velocity: f32,
    flags: u32,
    _pad0: u32,
    collision_group: u32,
    collision_mask: u32,
    _pad1: u32,
    _pad4: u32,
    com: vec3f,
    _pad2: f32,
    inverse_inertia: array<f32, 6>,
    _pad3: array<f32, 2>,
}

struct RowMove {
    row: u32,
    source: u32,
    fresh: u32,
    _pad: u32,
}

struct BodyEdit {
    kind: u32,
    mask: u32,
    _pad0: u32,
    _pad1: u32,
    state: BodyState,
}

struct BodyEditRun {
    row: u32,
    first: u32,
    len: u32,
    _pad: u32,
}

struct Collider {
    slot: u32,
    kind: u32,
    flags: u32,
    radius: f32,
    half_height: f32,
    half_extents: vec3f,
    collision_group: u32,
    local_offset: vec3f,
    collision_mask: u32,
    local_rotation: vec4f,
    friction: f32,
    restitution: f32,
    source: u32,
    rolling_friction: f32,
    scale: vec3f,
    spin_friction: f32,
}

struct ShapeSource {
    kind: u32,
    vertex_offset: u32,
    vertex_count: u32,
    triangle_offset: u32,
    triangle_count: u32,
    node_offset: u32,
    node_count: u32,
    _pad0: u32,
    local_min: vec3f,
    _pad1: f32,
    local_max: vec3f,
    _pad2: f32,
}

struct BvhNode {
    min: vec3f,
    _pad0: f32,
    max: vec3f,
    _pad1: f32,
    left: u32,
    right: u32,
    leaf: u32,
    _pad2: u32,
}

struct Triangle {
    a: u32,
    b: u32,
    c: u32,
    _pad0: u32,
}

struct Aabb {
    min: vec3f,
    _pad0: f32,
    max: vec3f,
    _pad1: f32,
}

struct ManifoldPoint {
    position: vec3f,
    depth: f32,
    accumulated_normal: f32,
    accumulated_tangent_1: f32,
    accumulated_tangent_2: f32,
    feature: u32,
}

struct Contact {
    a: u32,
    b: u32,
    point_count: u32,
    sensor: u32,
    first_body_id: u32,
    second_body_id: u32,
    first_generation: u32,
    second_generation: u32,
    normal: vec3f,
    events: u32,
    friction: f32,
    restitution: f32,
    rolling_friction: f32,
    spin_friction: f32,
    points: array<ManifoldPoint, CONTACT_MAX_POINTS>,
}

struct ConstraintDescriptor {
    kind: u32,
    a: u32,
    b: u32,
    flags: u32,
    anchor_a: vec3f,
    _pad1: f32,
    anchor_b: vec3f,
    _pad2: f32,
    axis_a: vec3f,
    _pad3: f32,
    axis_b: vec3f,
    _pad4: f32,
    distance: f32,
    limit_min: f32,
    limit_max: f32,
    swing_a: f32,
    swing_b: f32,
    motor_speed: f32,
    motor_max_force: f32,
    spring_frequency: f32,
    spring_damping_ratio: f32,
    break_force: f32,
    break_torque: f32,
    gear_ratio: f32,
    pulley_fixed_a: vec3f,
    _pad_pulley_a: f32,
    pulley_fixed_b: vec3f,
    _pad_pulley_b: f32,
    motor_target: f32,
    motor_stiffness: f32,
    motor_damping: f32,
    cone_angle: f32,
    reference: vec4f,
    linear_limit_min: vec3f,
    _pad_lim_min: f32,
    linear_limit_max: vec3f,
    _pad_lim_max: f32,
    angular_limit_min: vec3f,
    _pad_ang_min: f32,
    angular_limit_max: vec3f,
    _pad_ang_max: f32,
    linear_motor_target: vec3f,
    _pad_lin_target: f32,
    linear_motor_stiffness: vec3f,
    _pad_lin_stiff: f32,
    linear_motor_damping: vec3f,
    _pad_lin_damp: f32,
    angular_motor_target: vec3f,
    _pad_ang_target: f32,
    angular_motor_stiffness: vec3f,
    _pad_ang_stiff: f32,
    angular_motor_damping: vec3f,
    _pad_ang_damp: f32,
    linear_motor_force: vec3f,
    _pad_lin_force: f32,
    angular_motor_force: vec3f,
    _pad_ang_force: f32,
}

struct ConstraintRuntime {
    accumulated: array<f32, CONSTRAINT_ACCUMULATOR_SLOTS>,
    broken: u32,
    constraint_id: u32,
    generation: u32,
    _pad0: u32,
}

struct Query {
    kind: u32,
    shape_kind: u32,
    filter_flags: u32,
    slot: u32,
    group: u32,
    mask: u32,
    source: u32,
    max_hits: u32,
    exclude_id: u32,
    exclude_generation: u32,
    include_id: u32,
    include_generation: u32,
    origin: vec3f,
    _pad0: f32,
    direction: vec3f,
    extent: f32,
    radius: f32,
    half_height: f32,
    _pad1: f32,
    _pad2: f32,
    half_extents: vec3f,
    _pad3: f32,
    orientation: vec4f,
}

struct QueryResultHeader {
    count: atomic<u32>,
    overflow: atomic<u32>,
    _pad0: u32,
    _pad1: u32,
}

struct QueryHit {
    body_id: u32,
    body_generation: u32,
    distance: f32,
    collider_index: u32,
    point: vec3f,
    _pad1: f32,
    normal: vec3f,
    _pad2: f32,
}

struct QueryResult {
    header: QueryResultHeader,
    hits: array<QueryHit, MAX_HITS_PER_QUERY>,
}

struct ContactEvent {
    kind: u32,
    sensor: u32,
    first_id: u32,
    first_generation: u32,
    second_id: u32,
    second_generation: u32,
    point: vec3f,
    _pad0: f32,
    normal: vec3f,
    _pad1: f32,
}
