[package]
name = "dynamis-gpu"
version.workspace = true
edition.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true

[features]
profile = []

[dependencies]
dynamis-layout = { path = "../dynamis-layout" }
wgpu = { workspace = true }

[dev-dependencies]
pollster = { workspace = true }

[lints]
workspace = true
