mod body;
mod collider;
mod constant;
mod constraint;
mod counter;
mod decode;
mod param;
mod query;
mod row;

mod records {
    include!(concat!(env!("OUT_DIR"), "/records.rs"));
}
mod wgsl;

pub const ABI_WGSL: &str = include_str!("../abi/rigid.wgsl");

pub use constant::{
    BODY_CCD, BODY_KINEMATIC, COLLIDER_EVENT_BEGIN_END, COLLIDER_EVENT_PERSIST, COLLIDER_SENSOR,
    CONSTRAINT_BALL, CONSTRAINT_CONE, CONSTRAINT_DISABLE_COLLISIONS, CONSTRAINT_DISTANCE,
    CONSTRAINT_FIXED, CONSTRAINT_GEAR, CONSTRAINT_HAS_BREAK, CONSTRAINT_HAS_LIMIT,
    CONSTRAINT_HAS_MOTOR, CONSTRAINT_HAS_SWING, CONSTRAINT_IS_SPRING, CONSTRAINT_PRISMATIC,
    CONSTRAINT_PULLEY, CONSTRAINT_REVOLUTE, CONSTRAINT_SIXDOF, CONSTRAINT_WARM_START,
    CONTACT_ANNOUNCED, CONTACT_MAX_POINTS, DOF_DRIVEN, DOF_FREE, DOF_LIMITED, DOF_LOCKED,
    EDIT_ANGULAR_IMPULSE, EDIT_FORCE, EDIT_FORCE_AT_POINT, EDIT_IMPULSE, EDIT_IMPULSE_AT_POINT,
    EDIT_PATCH, EDIT_SLEEP, EDIT_TORQUE, EDIT_WAKE, EVENT_BEGIN, EVENT_END, EVENT_PERSIST,
    FILTER_IGNORE_KINEMATIC, FILTER_IGNORE_SENSORS, FILTER_IGNORE_SLEEPING, FILTER_IGNORE_STATIC,
    ISLAND_ACTIVE, ISLAND_WAKE, MAX_CELLS_PER_AXIS, MAX_CELLS_PER_COLLIDER, MAX_HITS_PER_QUERY,
    NO_BODY, NO_COLLISION_FILTER, NO_HIT, NO_SLOT, OVERRIDE_SLEEP_ANGULAR, OVERRIDE_SLEEP_LINEAR,
    PATCH_ANGULAR_VELOCITY, PATCH_ORIENTATION, PATCH_POSITION, PATCH_VELOCITY, QUERY_CONVEX,
    QUERY_CUBOID, QUERY_POINT, QUERY_RAY, QUERY_SPHERE, QUERY_SWEEP, SHAPE_CAPSULE, SHAPE_CUBOID,
    SHAPE_CYLINDER, SHAPE_HEIGHTFIELD, SHAPE_HULL, SHAPE_MESH, SHAPE_NONE, SHAPE_PLANE,
    SHAPE_SPHERE, SHAPE_TRIANGLE, SOLVER_BLOCK_CONSTRAINT, SOLVER_BLOCK_CONTACT, dof_mode,
};
pub use counter::{
    COUNTER_ACTIVE, COUNTER_ARCHIVED, COUNTER_BLOCKS, COUNTER_BODIES, COUNTER_BODY_EDITS,
    COUNTER_BODY_MOVES, COUNTER_COARSE_ACTIVE, COUNTER_CONSTRAINT_COMMANDS,
    COUNTER_CONSTRAINT_MOVES, COUNTER_CONSTRAINTS, COUNTER_CONTACTS, COUNTER_COUNT,
    COUNTER_ENTRIES, COUNTER_EVENTS, COUNTER_GRID_LEVELS, COUNTER_JOINTS, COUNTER_PAIRS,
    COUNTER_RESTING, COUNTER_RESTING_GATHER, COUNTER_RESTING_INDEX, COUNTER_RESTING_PENDING,
    COUNTER_SLEPT, COUNTER_SPILLOVER_ENTRIES, COUNTER_SPILLOVER_EVENTS, COUNTER_SPILLOVER_PAIRS,
    COUNTER_SPILLOVER_RESTING, COUNTER_STRIDE, COUNTER_WOKE, COUNTER_WOKE_DEFERRED, Counters,
};
pub use decode::decode;
pub use param::{FrameCounts, RowStreams};
pub use records::*;
pub use wgsl::constants_wgsl;
