[package]
name = "dynamis-character"
version.workspace = true
edition.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
dynamis-math = { workspace = true }
dynamis-model = { workspace = true }
dynamis-world = { workspace = true }

[dev-dependencies]
dynamis-gpu = { workspace = true }
pollster = { workspace = true }
