[package]
name = "dynamis-kernel"
version.workspace = true
edition.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
dynamis-gpu = { workspace = true }
dynamis-layout = { workspace = true }
wgpu = { workspace = true }

[dev-dependencies]
bytemuck = { workspace = true }
pollster = { workspace = true }

[lints]
workspace = true
