[package]
name = "dynamis-kernel"
version.workspace = true
edition.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
dynamis-abi = { workspace = true }
dynamis-pass = { workspace = true }
dynamis-gpu = { workspace = true }

[lints]
workspace = true
