[package]
name = "dynamis-pass"
version.workspace = true
edition.workspace = true
description = "Compute pass graph, scheduling, and shader binding"
license.workspace = true
repository.workspace = true

[features]
profile = ["dynamis-gpu/profile"]

[dependencies]
dynamis-gpu = { workspace = true }
dynamis-shader = { workspace = true }
wgpu = { workspace = true }

[dev-dependencies]
pollster = { workspace = true }

[lints]
workspace = true
