[package]
name = "dynamis-query"
version.workspace = true
edition.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
bytemuck = { workspace = true }
dynamis-layout = { workspace = true }
dynamis-model = { workspace = true }
