[package]
name = "dynamis-broadphase"
version.workspace = true
edition.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
dynamis-abi = { workspace = true }
dynamis-domain = { workspace = true }
dynamis-pass = { workspace = true }
dynamis-gpu = { workspace = true }
dynamis-kernel = { workspace = true }
dynamis-state = { workspace = true }
dynamis-sort = { workspace = true }
wgpu = { workspace = true }

[lints]
workspace = true
