[package]
name = "dynamis-sim"
version.workspace = true
edition.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
bytemuck = { workspace = true }
dynamis-gpu = { workspace = true }
dynamis-layout = { workspace = true }
dynamis-model = { workspace = true }
dynamis-query = { workspace = true }
wgpu = { workspace = true }

[dev-dependencies]
pollster = { workspace = true }
